services:
  courses_webinars_web:
    build:
      context: .
    container_name: courses_webinars_web
    hostname: courses_webinars_web
    ports:
      - "8000:8000"
    volumes:
      - ./courses_webinars:/courses_webinars
    env_file:
      - .env
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  celery_worker:
    build:
      context: .
    container_name: celery_worker
    hostname: celery_worker
    volumes:
      - ./courses_webinars:/courses_webinars
    env_file:
      - .env
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info

  celery_flower:
    build:
      context: .
    container_name: celery_flower
    hostname: celery_flower
    volumes:
      - ./courses_webinars:/courses_webinars
    env_file:
      - .env
    entrypoint: celery
    command: -A celery_app.app flower --loglevel=info
    ports:
      - "5555:5555"