# Generated by Django 4.2.3 on 2023-07-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('FILE', 'file'), ('PHOTO', 'photo'), ('MUSIC', 'music')], max_length=5),
        ),
        migrations.DeleteModel(
            name='MaterialType',
        ),
    ]
