# Generated by Django 4.2.3 on 2023-07-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='url',
            field=models.URLField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
