# Generated by Django 4.2.3 on 2023-07-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0002_remove_webinar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='music',
            name='url',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.URLField(max_length=300),
        ),
    ]
