# Generated by Django 4.2.3 on 2023-07-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0003_alter_file_url_alter_music_url_alter_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='author',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
