# Generated by Django 4.2.3 on 2023-07-25 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0010_lesson_root_module_module_root_module_and_more'),
        ('users', '0002_usertasklink'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRootModuleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_watched', models.BooleanField(default=False)),
                ('is_my', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'module')},
            },
        ),
        migrations.AlterField(
            model_name='usertasklink',
            name='task_id',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='UserModuleLink',
        ),
    ]
