# Generated by Django 4.2.3 on 2023-07-22 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0009_delete_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('VIDEO', 'video'), ('IMAGE', 'image'), ('AUDIO', 'audio')], max_length=5)),
                ('extension', models.CharField(max_length=5)),
                ('is_saved', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
            ],
        ),
    ]
