# Generated by Django 4.2.3 on 2023-07-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiallesson',
            name='type',
            field=models.CharField(choices=[('VIDEO', 'video'), ('IMAGE', 'image'), ('AUDIO', 'audio'), ('FILE', 'file')], max_length=5),
        ),
    ]
