# Generated by Django 4.2.3 on 2023-07-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_courses_is_watched_lessons_is_watched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinars',
            name='is_my',
            field=models.BooleanField(default=False),
        ),
    ]
