# Generated by Django 4.2.3 on 2023-07-13 15:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webinars', '0004_alter_webinar_author'),
        ('courses', '0001_initial'),
        ('users', '0003_webinars_is_my'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='UserCourseLink',
        ),
        migrations.RenameModel(
            old_name='Lessons',
            new_name='UserLessonLink',
        ),
        migrations.RenameModel(
            old_name='Webinars',
            new_name='UserWebinarLink',
        ),
    ]
