# Generated by Django 4.2.3 on 2023-07-14 17:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webinars', '0004_alter_webinar_author'),
        ('users', '0004_rename_courses_usercourselink_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userwebinarlink',
            unique_together={('user', 'webinar')},
        ),
    ]
