# Generated by Django 4.2.3 on 2023-07-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('VIDEO', 'video'), ('IMAGE', 'image'), ('AUDIO', 'audio')], max_length=5),
        ),
    ]
