# Generated by Django 4.2.3 on 2023-07-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='text',
            field=models.BinaryField(),
        ),
    ]
