# Generated by Django 4.2.3 on 2023-07-22 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_lesson_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
    ]
