# Generated by Django 4.2.3 on 2023-07-25 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_delete_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='root_module',
            field=models.ForeignKey(default=225, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_root_module', to='courses.module'),
        ),
        migrations.AddField(
            model_name='module',
            name='root_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_root_module', to='courses.module'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_parent', to='courses.module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_parent', to='courses.module'),
        ),
    ]
