# Generated by Django 4.2.3 on 2023-07-25 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_lesson_root_module_module_root_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='root_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_root_module', to='courses.module'),
        ),
    ]
